### ISSUE TITLE
404 responses and unicode characters not handled correctly

### ISSUE THREAD

**Issue by ToraenN** [ToraenN/buildpacks#62]
'–' (and likely other symbols) crash the script if they are in the build name. They're disallowed by the naming policy, but script still shouldn't crash because of them.

**Script output on crash**
Attempting Build:Team u2013 7 Hero Domination Mesmers for Paragon...
Traceback (most recent call last):
  File "C:\Users\wrenn\Desktop\bpe.py", line 246, in <module>
    result = get_build(pagelist.popleft())
  File "C:\Users\wrenn\Desktop\bpe.py", line 130, in get_build
    newpagename = newpagestr[0].replace('gwpvx.gamepedia.com/','').replace("')",'').replace('_',' ')
IndexError: list index out of range

**Comment by ToraenN** [comment]
So a unicode character will trigger a 301 or 302 response, and then it turns out I messed up in getting the new page name. This error affects every such response.

**Comment by ToraenN** [comment]
Using php instead of json as the returned format from the api should fix this.
